spring:
  datasource:
    url: jdbc:postgresql://localhost:9299/querydsl
    username: jpa
    password: asd098
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
#        use_sql_comments: true

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace